name: ci-update-sponsors

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - 'main'
    paths:
      - 'package.json'
      - 'sponsorkit.config.ts'

jobs:
  update-sponsors:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Print Contexts/Inputs/Variables/Secrets
        run: |
          echo "[Contexts]"
          echo "github.server_url = ${{ github.server_url }}"
          echo "github.repository = ${{ github.repository }}"
          echo "[Inputs]"
          echo "[Variables]"
          echo "[Secrets]"
          echo "secrets.SPONSORKIT_PATREON_TOKEN = ${{ secrets.SPONSORKIT_PATREON_TOKEN }}"
          echo "secrets.SPONSORKIT_AFDIAN_USER_ID = ${{ secrets.SPONSORKIT_AFDIAN_USER_ID }}"
          echo "secrets.SPONSORKIT_AFDIAN_TOKEN = ${{ secrets.SPONSORKIT_AFDIAN_TOKEN }}"

      - name: Checkout to '${{ github.ref }}'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Dependencies
        shell: bash
        run: npx pnpm install

      - name: Update Sponsors Files
        shell: bash
        run: npm run build
        env:
          SPONSORKIT_PATREON_TOKEN: ${{ secrets.SPONSORKIT_PATREON_TOKEN }}
          SPONSORKIT_AFDIAN_USER_ID: ${{ secrets.SPONSORKIT_AFDIAN_USER_ID }}
          SPONSORKIT_AFDIAN_TOKEN: ${{ secrets.SPONSORKIT_AFDIAN_TOKEN }}

      - name: Add and Commit the Changes
        id: acc
        uses: EndBug/add-and-commit@v9
        with:
          message: 'ðŸ”§ chore: update sponsors files'
          add: './static/*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Outputs of the Commit
        if: steps.acc.outputs.committed == 'true'
        shell: bash
        run: |
          echo "Commit's URL = ${{ github.server_url }}/${{ github.repository }}/commit/${{ steps.acc.outputs.commit_long_sha }}"
          echo "Commit's SHA = ${{ steps.acc.outputs.commit_long_sha }}"
